intel/intel-extension-for-pytorch

cmake/CPU.cmake
tests/cpu/test_lazy_reorder.py
tests/cpu/test_rn50_cpu_ops.py
tests/cpu/test_torch.py
torch_ipex/csrc/aten_ipex_bridge.cpp
torch_ipex/csrc/cpu/DevOPs.cpp
torch_ipex/csrc/cpu/ShadeDataContext.h
torch_ipex/csrc/cpu/dbl/Common.cpp
torch_ipex/csrc/cpu/dbl/Common.h
torch_ipex/csrc/cpu/dbl/DNNLChecker.cpp
torch_ipex/csrc/cpu/dbl/DNNLChecker.h
torch_ipex/csrc/utils.cpp

We should just take the DNNL tensor as the buffer of aten tensor. It means that the shape information for OP computation should come from aten tensor but not its buffer - DNNL tensor. Then we can refine DNNL OP as follows.
- Attach the shape meta info of aten tensor to DNNL tensor at the DNNL OP entry point
- Write the shape meta info of DNNL tensor back to its aten tensor wrapper.
Besides that, if the OP(ex, slice, view) could change the shape of a tensor, its input tensors will always be reordered to a public format. Then its output tensors will be the plain format.

Sync the strides and size of DNNL tensor to its aten::tensor wrapper

---

scripts/cpu/gen-dense-cpu-ops.py
tests/cpu/test_torch.py
torch_ipex/csrc/cpu/dbl/Common.cpp
torch_ipex/csrc/cpu/dbl/DNNLChecker.cpp
torch_ipex/csrc/cpu/dil/dil/tensor.hpp

@pinzhenx @hongzhen1 @jiayisunx @XiaobingSuper , Please review the patch to make sure the shape of aten tensor and its dil tensor buffer is consistent. The dil tensor is just a buffer of aten tensor, all shape info for the computation should come from the aten tensor. 
@pinzhenx , I'm not sure which DNNL OP requires its input tensors should be contiguous. Could you help to check it?
After that, each DNNL op needs to do "contiguous" explicitly if it requires its input tensors are contiguous.

Sync shape info between dil tensor and aten tensor

---

scripts/cpu/gen-dense-cpu-ops.py
tests/cpu/test_lazy_reorder.py
torch_ipex/csrc/aten_ipex_bridge.cpp
torch_ipex/csrc/cpu/DevOPs.cpp
torch_ipex/csrc/cpu/ShadeDataContext.h
torch_ipex/csrc/cpu/dbl/Common.cpp
torch_ipex/csrc/init_python_bindings.cpp
torch_ipex/csrc/utils.cpp
torch_ipex/csrc/utils.h

1. Make sure all input tensors of DNNL OP are contiguous
2. Expose some DNNL interface to PyThon to check if a tensor is dil tensor for unit test
3. Fix the issue that didn't check if the tensor own whole storage
4. Write the shape meta info back to aten tensor if the tensor is reordered to public format

Refine unit test case and write the shape meta info back to aten tensor when the tensor is reordered to public format

---

cmake/CPU.cmake
scripts/cpu/gen-dense-cpu-ops.py
scripts/cpu/gen-sparse-cpu-ops.py
torch_ipex/csrc/aten_ipex_bridge.cpp
torch_ipex/csrc/aten_ipex_bridge.h
torch_ipex/csrc/cpu/DevOPs.cpp
torch_ipex/csrc/cpu/ExtendOPs.cpp
torch_ipex/csrc/cpu/MlpOPs.cpp
torch_ipex/csrc/cpu/ShadeDataContext.h
torch_ipex/csrc/cpu/SparseAttr.cpp
torch_ipex/csrc/cpu/dbl/Common.cpp
torch_ipex/csrc/ipex_sparse_tensor_impl.cpp
torch_ipex/csrc/ipex_tensor_impl.cpp
torch_ipex/csrc/jit/fusion_pass.cpp

TORCH_INTERNAL_ASSERT is not only for debug but also for release. I replaced it by TORCH_INTERNAL_ASSERT_DEBUG_ONLY. TORCH_INTERNAL_ASSERT_DEBUG_ONLY is only enabled in debug.

Refine assert IPEX

---

tests/cpu/test_lazy_reorder.py
torch_ipex/csrc/cpu/DevOPs.cpp
torch_ipex/csrc/cpu/ShadeDataContext.h
torch_ipex/csrc/cpu/dbl/Common.cpp

IPEX does not support the case as follows.
1. The buffer of Aten tensor is DNNL buffer and its format is block-format
2. The buffer does not occupy whole storage
I add a more critical check for debugging.

Check DNNL Buffer

---

torch_ipex/csrc/aten_ipex_bridge.cpp
torch_ipex/csrc/aten_ipex_bridge.h
torch_ipex/csrc/cpu/DevOPs.cpp
torch_ipex/csrc/cpu/ShadeDataContext.h
torch_ipex/csrc/cpu/dbl/Common.cpp
torch_ipex/csrc/cpu/dbl/Common.h
torch_ipex/csrc/cpu/dbl/Pool.cpp

This PR is to optimize the dispatcher for aten ops:
- optimize out dummy dil tensor creation in `ShadeDataContext`
We noticed the creation of dummy DIL tensor in `ShadeDataContext` cost a significant amount of time. So I change the `dil_tensor` field to optional.
- use move semantics in `gen_aten_tensor_by`
Avoid the unnecessary shallow copy of tensors. Hence we're going to use it this way with a `std::move`.
```cpp
at::Tensor AtenIpexCPUDev::foo(const at::Tensor& x) {
dil::tensor y;
...
return dbl::comm::gen_aten_tensor_by(std::move(y));
}
```
------
**This PR reduce the dispatcher overhead from 90%+ to 20%+.** The result was gathered under single thread with jemalloc enabled. The remaining gap is mostly cost by `shallowUpgradeToDPCPPTensor`. That's where we need to optimize in the …

use optional dil tensor & move semantics

---

intel_pytorch_extension_py/ops/embeddingbag.py
torch_ipex/csrc/cpu/CMakeLists.txt
torch_ipex/csrc/cpu/ExtendOPs.cpp
torch_ipex/csrc/cpu/ExtendOPs.h
torch_ipex/csrc/cpu/aten/aten.hpp
torch_ipex/csrc/cpu/aten/operators/embedding_bag.cpp
torch_ipex/csrc/cpu/aten/operators/embedding_bag.hpp
torch_ipex/csrc/cpu/bf16/vec/bf16_vec_kernel.h
torch_ipex/csrc/init_python_bindings.cpp

This is to enhance the Embedding Bag Sum Fast Support for FP32 and BFloat16 with aligned parameter s in embedding_bag and embedding_bag_backward for both sparse and dense embedding tables. Also enhance some BF16 related vectorization functions.

Embedding Bag Sum Fast Support for FP32 and BFloat16

---

tests/cpu/common_ipex_conf.py
tests/cpu/test_bf16_lazy_reorder.py
torch_ipex/csrc/aten_ipex_bridge.cpp
torch_ipex/csrc/cpu/DevOPs.cpp
torch_ipex/csrc/cpu/ShadeDataContext.h
torch_ipex/csrc/cpu/dbl/Common.cpp
torch_ipex/csrc/cpu/dbl/Common.h
torch_ipex/csrc/init_python_bindings.cpp
torch_ipex/csrc/utils.cpp
torch_ipex/csrc/utils.h

We currently hide the BF16 data type in DNNL buffer and IPEX always represents the tensor as Float32. If the OP supports BFloat16, IPEX will reorder the buffer to BFloat16 and attach the bf16 buffer to the aten tensor. However, it still is in-place reorder, there might be issues for multi-instances inference.
@pinzhenx , could you help to check the correctness of the DNNL OPs in DevOPs? I will add more unit test cases.

Lazy reorder for bf16

---

tests/cpu/test_jit.py
torch_ipex/csrc/cpu/Prepack.cpp
torch_ipex/csrc/cpu/Prepack.h
torch_ipex/csrc/init_python_bindings.cpp
torch_ipex/csrc/jit/CMakeLists.txt
torch_ipex/csrc/jit/prepack_weight.cpp
torch_ipex/csrc/jit/prepack_weight.h

For jit path, the users can prepack DNNL convolution's weight by following steps:
```
modle = MyModel().to('dpcpp").eval()
scripted= torch.jit.script(model)
scripted = wrap_cpp_module(core._jit_prepack_conv_weight(scripted._c))
```

jit: enable prepack dnnl convolution's weight

---

intel_pytorch_extension_py/__init__.py
intel_pytorch_extension_py/tensor.py

`copy.deepcopy` will trigger a check that the current backend supports the storage with the specified data type. But PyTorch only registers different data type storages for CPU and CUDA, so the check will fail. IPEX rewrites the `__deepcopy__` of tensor by `clone` to work around it.
@zhuhaozhe @pinzhenx @hongzhen1

Override tensor copy to support deepcopy

---

torch_ipex/csrc/cpu/aten/operators/embedding_bag.cpp

Fix "test_nn.py -v TestNNDeviceTypeCPU.test_EmbeddingBag_per_sample_weights_and_new_offsets_cpu" test failure

Fix EmbeddingBag unit test failure

---

intel_pytorch_extension_py/ops/__init__.py
tests/cpu/test_lazy_reorder.py
torch_ipex/csrc/cpu/DevOPs.cpp
torch_ipex/csrc/cpu/dbl/DNNLChecker.cpp
torch_ipex/csrc/cpu/dbl/DNNLChecker.h

- force all inputs to be dpcpp tensor
- fix convolution_overrideable cannot be fallbacked to cpu. Fix #60

force all inputs to be dpcpp tensor

---

intel_pytorch_extension_py/ops/jit_script.py
scripts/cpu/gen-dense-cpu-ops.py
tests/cpu/test_bf16_lazy_reorder.py
tests/cpu/test_lazy_reorder.py
torch_ipex/csrc/cpu/DevOPs.cpp
torch_ipex/csrc/cpu/DevOPs.h
torch_ipex/csrc/cpu/dbl/Common.cpp

Refine all matmul and binary ops

---

intel_pytorch_extension_py/ops/jit_script.py
torch_ipex/csrc/cpu/DevOPs.cpp

Disable mix precision in model fusion, since mixed precision in fusion cannot bring any benefits for inference, but will lead to a little bit loss of accuracy, noticed by @jiayisunx

disable mixed precision in bn fusion & clone

---

torch_ipex/csrc/aten_ipex_bridge.cpp

Currently `shallowFallbackToCPUTensorList` called `shallowFallbackToCPUTensorImpl` instead of `shallowFallbackToCPUTensor`.
The latter one will additionally fallback dil tensor back to public tensor, so ops that calling `shallowFallbackToCPUTensorList`, like `cat`, will lose the opportunity to fallback, which causes segfault in `at::cat`

fix shallowFallbackToCPUTensorList

---

intel_pytorch_extension_py/ops/pooling.py

hook torch.adaptive_avg_pool2d instead of F.adaptive_avg_pool2d to fix jit script error on adaptive_avg_pool2d

fix jit script error on adaptive_avg_pool2d

---

intel_pytorch_extension_py/ops/jit.py

when we convert a function to a scripted or traced module, there always has the following error:
```
File "/home/xiaobinz/anaconda3/envs/pytorch-test/lib/python3.6/site-packages/torch/jit/__init__.py", line 551, in _check_trace
_module_class=_module_class,
File "/home/xiaobinz/anaconda3/envs/pytorch-test/lib/python3.6/site-packages/torch_ipex-0.1-py3.6-linux-x86_64.egg/intel_pytorch_extension/ops/jit.py", line 37, in trace_
jit_m = wrap_cpp_module(torch._C._jit_pass_fold_convbn(jit_m._c))
AttributeError: 'torch._C.ScriptFunction' object has no attribute '_c'
```
this PR fix it.

fix torch._C.ScriptFunction' object has no attribute '_c' problem when convert a function to scripted or traced module

---

tests/cpu/common_nn.py
tests/cpu/test_bf16_lazy_reorder.py
tests/cpu/test_rn50_cpu_ops.py
tests/cpu/test_torch.py

mark three known issues as expected failures.
Before our CI get deployed, now we can run all tests simply with
```
python -m pytest -v tests/cpu/*
```

mark expected failure test cases

---

intel_pytorch_extension_py/ops/jit.py

Now, **intel_pytorch_extension_py** import **jit** module in [```__init__.py```](https://github.com/intel/intel-extension-for-pytorch/blob/master/intel_pytorch_extension_py/__init__.py), but [jit.py](https://github.com/intel/intel-extension-for-pytorch/blob/master/intel_pytorch_extension_py/__init__.py) file also import **intel_pytorch_extension_py** , there has a circular import, may have potential issue in the future,  see https://stackabuse.com/python-circular-imports/, so we need avoid using it.

avoid python circular import

---

docker/Dockerfile

As a fix for issue - https://github.com/intel/intel-extension-for-pytorch/issues/155. As suggested by @jingxu10, adding pybind11-dev allows for a successful build of the Docker container.

Update Dockerfile to include pybind11-dev

---

README.md

Currently the sample produces the following error:
```
/home/workflow-arc/pyenvs/ipt39/lib/python3.9/site-packages/intel_extension_for_pytorch/frontend.py:277: UserWarning: pending the optimization for LSTM
warnings.warn("pending the optimization for LSTM")
Traceback (most recent call last):
File "/home/workflow-arc/code/intel-extension-for-pytorch/../ipt_samples/gpu_inf.py", line 15, in <module>
model(data)
File "/home/workflow-arc/pyenvs/ipt39/lib/python3.9/site-packages/torch/fx/graph_module.py", line 616, in wrapped_call
raise e.with_traceback(None)
RuntimeError: Input type (torch.FloatTensor) and weight type (XPUFloatType) should be the same or input should be a MKLDNN tensor and weight is a dense tensor
```
Method torch.Tensor.to() returns a copy of the tensor located on the …

Fix xpu sample in readme

---

intel_extension_for_pytorch/_inductor/xpu/triton_heuristics.py

This commit cherry-picks from the following changes from PyTorch:
- https://github.com/pytorch/pytorch/pull/123076
- https://github.com/pytorch/pytorch/issues/119450
It is used to co-work with API changes in https://github.com/intel/intel-xpu-backend-for-triton/issues/830

[inductor] make inductor work with new triton kernel launch API

---

intel_extension_for_pytorch/_inductor/xpu/triton_heuristics.py

Since we can get device architecture by sycl::device from 2024.1. https://github.com/intel/llvm/blob/b963e894678247d99b03f18d00ae7bdc4ca883da/sycl/include/sycl/ext/oneapi/experimental/device_architecture.hpp#L18 We are trying to get arch infomations from Triton side to decouple with IPEX. This may reduce the maintaining efforts. This is only for Triton testing now.

[Triton] change target[1] to sycl_device to get arch properties from Triton side

---

csrc/gpu/aten/core/DeviceInfo.h
csrc/gpu/runtime/Device.cpp
csrc/gpu/runtime/DeviceProp.h
csrc/gpu/utils/DPCPP.h
intel_extension_for_pytorch/_inductor/xpu/triton_heuristics.py
intel_extension_for_pytorch/csrc/xpu/Module.cpp

Add device arch to DeviceInfo cause Triton needs it during compilation.

Add device architecture to DeviceInfo

---

intel_extension_for_pytorch/_inductor/xpu/triton_heuristics.py

Reverts intel/intel-extension-for-pytorch#590

Revert "[Triton] change target[1] to sycl_device to get arch properties from Triton side"

---

csrc/gpu/aten/core/DeviceInfo.h
csrc/gpu/runtime/Device.cpp
csrc/gpu/runtime/DeviceProp.h
intel_extension_for_pytorch/csrc/xpu/Module.cpp

Triton want to leverage `ext_oneapi_supports_cl_extension` to query the backend instruction supportance.
@Stonepia can you help take a look and merge it into triton dev branch?

Check extension supportance via `ext_oneapi_supports_cl_extension`

---

csrc/gpu/aten/core/DeviceInfo.h
csrc/gpu/runtime/Device.cpp
csrc/gpu/runtime/DeviceProp.h
intel_extension_for_pytorch/csrc/xpu/Module.cpp

The corresponding change in https://github.com/pytorch/pytorch/commit/08860b26f18e78efa14f033f33f0199ac0f66370
Target: https://github.com/intel/intel-xpu-backend-for-triton/issues/1787

Update bfloat16 conversion property

---

tests/cpu/bench/custom_op_bench/README.md

Small PR - Commit f63ed979891f28d073a67fa4cd1b3e4fb1c1b3a9 moved bunch of files. This PR adjusts source for changes.

Update Custom OPs broken references
