intel/intel-extension-for-pytorch

cmake/CPU.cmake, cmake/Modules/FindAVX.cmake
=> Interrupt building system on machines without AVX512.

torch_ipex/csrc/cpu/bf16/vec/bf16_vec_kernel.h
To fix DLRM BF16 training error
=> Fix bf16 move_ker bug

intel_pytorch_extension_py/ops/linear.py, intel_pytorch_extension_py/ops/pooling.py, torch_ipex/csrc/cpu/ExtendOPs.cpp, torch_ipex/csrc/cpu/ExtendOPs.h
Make torch_ipex.linear bias parameter can be None.
=> enable linear bias can be None

tests/cpu/test_jit.py, torch_ipex/csrc/cpu/FusionOPs.cpp, torch_ipex/csrc/cpu/FusionOPs.h, torch_ipex/csrc/jit/fusion_pass.cpp, torch_ipex/csrc/jit/register_dnnl_jit_ops.cpp
=> jit: enable linear relu fusion

torch_ipex/csrc/cpu/CMakeLists.txt, torch_ipex/csrc/cpu/toolkit/sklearn.cpp, torch_ipex/csrc/cpu/toolkit/sklearn.h, torch_ipex/csrc/init_python_bindings.cpp
=> add optimization for sklearn

tests/cpu/test_jit.py, torch_patches/dpcpp-v1.5-rc3.patch
1.  Making conv_bn_folding can works for traced module.
2. Enable conv3d and BatchNorm3d fusion.
=> apply #34932 patch to enable trace module' conv_bn_folding and also enable 3d case

README.md, intel_pytorch_extension_py/__init__.py, intel_pytorch_extension_py/ops/jit_script.py, tests/cpu/common_ipex_conf.py, tests/cpu/test_conf.py, tests/cpu/test_jit.py, tests/cpu/test_lazy_reorder.py, tests/cpu/test_rn50_cpu_ops.py, torch_ipex/csrc/auto_opt_config.h, torch_ipex/csrc/init_python_bindings.cpp
1. Refine README
2. Refine Python API
=> Refine README and API

torch_ipex/csrc/cpu/DevOPs.cpp, torch_ipex/csrc/cpu/FusionOPs.cpp, torch_ipex/csrc/utils.h
=> replace TORCH_CHECK with IPEX_CHECK for fast fallback

torch_ipex/csrc/cpu/dbl/Common.cpp
Reverts intel/intel-extension-for-pytorch#58
=> Revert "Haozhe dev"

torch_patches/dpcpp-v1.5-rc3.patch
=> add dpcpp attribute for Tensor class

tests/cpu/test_bf16_lazy_reorder.py, tests/cpu/test_lazy_reorder.py, torch_ipex/csrc/cpu/DevOPs.cpp, torch_ipex/csrc/cpu/DevOPs.h, torch_ipex/csrc/cpu/FusionOPs.cpp, torch_ipex/csrc/cpu/dbl/Conv.cpp, torch_ipex/csrc/cpu/dbl/Conv.h, torch_ipex/csrc/cpu/dbl/Deconv.cpp, torch_ipex/csrc/cpu/dbl/Deconv.h
Fix https://github.com/intel/intel-extension-for-pytorch/issues/80 forward path.
=> fix conv transpose dispatch into wrong kernel for forward path

tests/cpu/test_jit.py, torch_ipex/csrc/jit/fusion_pass.cpp
ensure that the nodes to be fused have the same owning block
=> add check on the owning block of nodes to be fused

docker/Dockerfile
Experimental docker support, tested with TorchVision models.
=> add initial Dockerfile

intel_pytorch_extension_py/ops/embeddingbag.py, torch_ipex/csrc/cpu/aten/operators/embedding_bag.cpp
=> memory footprint reduction for dlrm inference

intel_pytorch_extension_py/ops/embeddingbag.py
=> remove package dependency

.gitmodules, intel_pytorch_extension_py/ops/linear_fuse_relu.py, torch_ipex/csrc/cpu/DevOPs.cpp, torch_ipex/csrc/cpu/DevOPs.h, torch_ipex/csrc/cpu/ExtendOPs.cpp, torch_ipex/csrc/cpu/ExtendOPs.h, torch_ipex/csrc/cpu/dil/dil/operators/inner_product.hpp, torch_ipex/csrc/init_python_bindings.cpp
Signed-off-by: haozhezh <haozhe.zhu@intel.com>
=> BRGEMM based InnerProduct

docker/README.md
If use linux kernel 4.15 that is default of Ubuntu18.04 in host, we can not build "docker/Dockerfile", get the following error message.
```console
#14 376.0 Traceback (most recent call last):
#14 376.0   File "setup.py", line 745, in <module>
#14 376.0     build_deps()
#14 376.0   File "setup.py", line 311, in build_deps
#14 376.0     build_caffe2(version=version,
#14 376.0   File "/intel-extension-for-pytorch/pytorch/tools/build_pytorch_libs.py", line 62, in build_caffe2
#14 376.0     cmake.build(my_env)
#14 376.0   File "/intel-extension-for-pytorch/pytorch/tools/setup_helpers/cmake.py", line 339, in build
#14 376.0     self.run(build_args, my_env)
#14 376.0   File "/intel-extension-for-pytorch/pytorch/tools/setup_helpers/cmake.py", line 141, in run
#14 376.0     check_call(command, …
```
=> add document for docker

docker/Dockerfile, docker/README.md, docs/tutorials/features/graph_optimization.md, docs/tutorials/releases.md
Signed-off-by: Abolfazl Shahbazi <abolfazl.shahbazi@intel.com>
=> Update docs and Dockerfile for v1.10.0

intel_extension_for_pytorch/cpu/launch.py
The doc in ipex launch script is outdated, this PR only updated the doc.
=> Update ipex launch doc

setup.py
This reverts commit 27ece6c73ec8c47a5a0215167b8a8705ad80b443.
=> Revert 27ece6c for build issue

README.md
Method torch.Tensor.to() returns a copy of the tensor located on the specified device, while the original tensor is not moved.
=> Fix xpu sample in readme

csrc/gpu/aten/core/DeviceInfo.h, csrc/gpu/runtime/Device.cpp, csrc/gpu/runtime/DeviceProp.h, intel_extension_for_pytorch/csrc/xpu/Module.cpp
Update property names so they are similar to https://github.com/pytorch/pytorch/pull/131738 both in IPEX and here
Targets: https://github.com/intel/intel-xpu-backend-for-triton/issues/1787
=> Update device property names
